name: Build examples

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@master

      - name: Configure and Build
        shell: cmd # Often helpful on Windows for cmake/msvc
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DJUCE_BLUETOOTH_BUILD_EXAMPLES=ON -DCPM_SOURCE_CACHE=build
          cmake --build build

  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Configure and Build
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DJUCE_BLUETOOTH_BUILD_EXAMPLES=ON -DCPM_SOURCE_CACHE=build
          cmake --build build

  build-linux:
    name: Build on Linux (Nix)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - run: nix flake check -L --all-systems

      - name: Configure and Build (Nix)
        run: |
          nix develop --command cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DJUCE_BLUETOOTH_BUILD_EXAMPLES=ON -DCPM_SOURCE_CACHE=build
          nix develop --command cmake --build build
